server:
  log_level: info

metrics:
  wal_directory: /tmp/wal
  global:
    scrape_interval: 15s
  configs:
    - name: blackbox
      scrape_configs:
        - job_name: blackbox
          metrics_path: /probe
          params:
            module: [http_2xx]
          static_configs:
            - targets:
              - https://project-medilink.onrender.com
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - target_label: __address__
              replacement: project-medilink.onrender.com:9115

      remote_write:
        - url: https://prometheus-prod-53-prod-me-central-1.grafana.net/api/prom
          basic_auth:
            username: ${GRAFANA_INSTANCE_ID}
            password: ${GRAFANA_API_KEY}